Regularize whitespace; add editorconfig
- Change the few files that use leading tabs into leading spaces.
  This way they match the other files in the repo.
- Add an EditorConfig file so that supported editors will automatically
  use spaces instead of tabs.
- (Extra) Add some common editor backup-file extensions to .gitignore.

diff --git a/utils/index-all-repositories b/utils/index-all-repositories
--- a/utils/index-all-repositories
+++ b/utils/index-all-repositories
@@ -19,9 +19,9 @@ index() {
 
     if [ "$remote" != "" ]
     then
-	cd $LXR_REPO_DIR
-	git remote add other $remote
-	git fetch other
+        cd $LXR_REPO_DIR
+        git remote add other $remote
+        git fetch other
     fi
 
     cd $ELIXIR_INSTALL
@@ -37,16 +37,16 @@ index() {
 
 if [ "$ELIXIR_ROOT" = "" ]
 then
-	echo "Error: ELIXIR_ROOT environment variable not set"
-	echo "It's where Elixir data are stored"
-	exit 1
+    echo "Error: ELIXIR_ROOT environment variable not set"
+    echo "It's where Elixir data are stored"
+    exit 1
 fi
 
 if [ "$ELIXIR_INSTALL" = "" ]
 then
-	echo "Error: ELIXIR_INSTALL environment variable not set"
-	echo "It's where Elixir code is stored"
-	exit 1
+    echo "Error: ELIXIR_INSTALL environment variable not set"
+    echo "It's where Elixir code is stored"
+    exit 1
 fi
 
 index amazon-freertos https://github.com/aws/amazon-freertos.git &
